### PR TITLE
Support Next.js 13

### PR DESCRIPTION
**Pull request by partounian**

### CODE REVIEW

**Comment by partounian** [comment]
Can also consider using >= 9?

**Comment by RyanClementsHax** [comment]
Thanks for opening this.

Can you also add a next v13 example? I use those folders to test for regressions but also give people a working example to start with. A link to it on the readme would also need to be added.

**Comment by partounian** [comment]
Pushed up your requested updates. What are your thoughts on changing the example, or creating a separate example that uses the next app dir functionality?

I know it's experimental, but I imagine it is the primary reason for users upgrading to 13.

**Comment by bonesoul** [comment]
looking for this to get merged :)

**Comment by bonesoul** [comment]
any updates?

**Comment by partounian** [comment]
Sorry, I keep forgetting to update this stuff. I'll set a reminder to work on this tonight if time allows. 

Feel free to pick up this PR, or start a new one if you're in a rush. I've been using `--force` when I was using this addon a couple weeks ago with NextJS 13.

**Pull request merged**
