### PR TITLE
fix: fix undefined "generator.filename" option

### LINKED ISSUE #100: Does not work with `@nrwl/react/plugins/storybook` addon
### Describe the bug

Storybook gives the error:

```
ModuleBuildError: Module build failed (from ./node_modules/storybook-addon-next/dist/images/next-image-loader-stub.js):
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.nextImageLoaderStub (/Users/anatoo/Workspace/xxx/xxx/node_modules/storybook-addon-next/dist/images/next-image-loader-stub.js:7:75)
    at processResult (/Users/anatoo/Workspace/xxx/xxx/node_modules/webpack/lib/NormalModule.js:758:19)
    at /Users/anatoo/Workspace/xxx/xxx/node_modules/webpack/lib/NormalModule.js:860:5
    at /Users/anatoo/Workspace/xxx/xxx/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /Users/anatoo/Workspace/xxx/xxx/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at runSyncOrAsync (/Users/anatoo/Workspace/xxx/xxx/node_modules/loader-runner/lib/LoaderRunner.js:156:3)
    at iterateNormalLoaders (/Users/anatoo/Workspace/xxx/xxx/node_modules/loader-runner/lib/LoaderRunner.js:251:2)
    at /Users/anatoo/Workspace/xxx/xxx/node_modules/loader-runner/lib/LoaderRunner.js:224:4
    at /Users/anatoo/Workspace/xxx/xxx/node_modules/webpack/lib/NormalModule.js:834:15
    at Array.eval (eval at create (/Users/anatoo/Workspace/xxx/xxx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at runCallbacks (/Users/anatoo/Workspace/xxx/xxx/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
```

### Your minimal, reproducible example

None

### Steps to reproduce

1. Add `@nrwl/react/plugins/storybook` addon to ".storybook/main.js"
3. Run storybook but it just fail with the above error

### Expected behavior

Storybook start normally

### How often does this bug happen?

Every time

### Screenshots or Videos

_No response_

### Platform

 - OS: macOS

### storybook-addon-next version

v1.6.7

### Additional context

`@nrwl/react/plugin/storybook` add the below webpack loader rule.

```
{
  test: /\.(bmp|png|jpe?g|gif|webp|avif)$/,
  type: 'asset',
  parser: { dataUrlCondition: { maxSize: 10000 } }
} 
```

`storybook-addon-next` 's `configureStaticImageImport` function refer `generator.filename` option of the rule.
```typescript
  const assetRule = rules?.find(
    rule =>
      typeof rule !== 'string' &&
      rule.test instanceof RegExp &&
      rule.test.test('test.jpg')
  ) as RuleSetRule
  assetRule.test = /\.(apng|eot|otf|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/
  rules?.push({
    test: /\.(png|jpg|jpeg|gif|webp|avif|ico|bmp|svg)$/i,
    issuer: { not: /\.(css|scss|sass)$/ },
    use: [
      {
        loader: require.resolve('./next-image-loader-stub'),
        options: {
          filename: assetRule.generator?.filename // <<----
        }
      }
    ]
  })
  rules?.push({
    test: /\.(png|jpg|jpeg|gif|webp|avif|ico|bmp|svg)$/i,
    issuer: /\.(css|scss|sass)$/,
    type: 'asset/resource',
    generator: {
      filename: assetRule.generator?.filename // <<----
    }
  })
``` 
https://github.com/RyanClementsHax/storybook-addon-next/blob/main/src/images/webpack.ts#L15-L41

As a result, the `generator.filename` option is undefined and the storybook is broken.

### PR DESCRIPTION
**Pull request by anatoo**
fixes #100

### CODE REVIEW

**Comment by puku0x** [comment]
@RyanClementsHax Could you reopen and review this PR, please?

With https://github.com/nrwl/nx/pull/12276 and the fallbacks in this PR, the issue #100 should be solved👍

**Comment by mandarini** [comment]
Hi there @RyanClementsHax ! Can you please take a look at this, and please reopen? Let me know if you need any help reviewing! It would really help with the Nx integration!

**Comment by mandarini** [comment]
Thank you SO much @RyanClementsHax !!!! :D

**Comment by RyanClementsHax** [comment]
No prob thanks for helping to test :)

**Comment by daves28** [comment]
The issue that this fixed is currently present in the @storybook/nextjs framework. I can make a PR to copy this change over to that as well.

**Comment by RyanClementsHax** [comment]
I'd be happy to review any PRs :)

**Pull request merged**
