### PR TITLE
fixes module resolution to support hoisting (E.g. yarn workspaces)

### LINKED ISSUE #23: Does not work with yarn workspaces
### Describe the bug

When using in a project that is a [yarn workspace](https://classic.yarnpkg.com/lang/en/docs/workspaces/) (on a monorepo setup), the plugin fails to find modules because of node_modules being hoisted up to the root folder:

```
yarn storybook
yarn run v1.22.17
$ start-storybook -p 6006 -s public
info @storybook/react v6.4.18
info 
(node:61699) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Serving static files from ./public at /
info => Using implicit CSS loaders
ERR! Error: Cannot find module '<project-root>/storybook-addon-next/examples/with-tailwindcss/node_modules/next/package.json'
ERR! Require stack:
ERR! - <project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/utils.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/preset.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core-common/dist/cjs/presets.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core-common/dist/cjs/index.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core/dist/cjs/server.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core/server.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/react/dist/cjs/server/index.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at getNextjsVersion (<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/utils.js:9:1)
ERR!     at configureStaticImageImport (<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/images/webpack.js:14:50)
ERR!     at configureImages (<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/images/webpack.js:8:5)
ERR!     at <project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/preset.js:29:35
ERR!     at Generator.next (<anonymous>)
ERR!     at fulfilled (<project-root>/storybook-addon-next/examples/node_modules/tslib/tslib.js:114:62)
ERR!  Error: Cannot find module '<project-root>/storybook-addon-next/examples/with-tailwindcss/node_modules/next/package.json'
ERR! Require stack:
ERR! - <project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/utils.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/preset.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core-common/dist/cjs/presets.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core-common/dist/cjs/index.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core/dist/cjs/server.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/core/server.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/react/dist/cjs/server/index.js
ERR! - <project-root>/storybook-addon-next/examples/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at getNextjsVersion (<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/utils.js:9:1)
ERR!     at configureStaticImageImport (<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/images/webpack.js:14:50)
ERR!     at configureImages (<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/images/webpack.js:8:5)
ERR!     at <project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/preset.js:29:35
ERR!     at Generator.next (<anonymous>)
ERR!     at fulfilled (<project-root>/storybook-addon-next/examples/node_modules/tslib/tslib.js:114:62) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/utils.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/storybook-addon-next/dist/preset.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/core-common/dist/cjs/presets.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/core-common/dist/cjs/index.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/core-server/dist/cjs/index.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/core/dist/cjs/server.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/core/server.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/react/dist/cjs/server/index.js',
ERR!     '<project-root>/storybook-addon-next/examples/node_modules/@storybook/react/bin/index.js'
ERR!   ]
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Your minimal, reproducible example

https://github.com/volkyeth/storybook-addon-next/tree/broken-with-yarn-workspaces

### Steps to reproduce

```
git clone --branch broken-with-yarn-workspaces git@github.com:volkyeth/storybook-addon-next.git
cd storybook-addon-next/examples
yarn install
cd with-tailwindcss
yarn storybook
```

### Expected behavior

Package should work with yarn workspaces

### How often does this bug happen?

Every time

### Screenshots or Videos

_No response_

### Platform

OS: MacOS

### storybook-addon-next version

1.4.2

### Additional context

I'm not sure what's the fix for this as I'm not very experienced at packaging libs. I'll try to look into it but if someone knows how to make it compatible please advise and I'll try to make a PR

### PR DESCRIPTION
**Pull request by volkyeth**
Decouples module resolution from the regular node_modules folder structure to support hoisting in
solutions like Yarn workspaces

Fixes #23

### CODE REVIEW

**Comment by RyanClementsHax** [comment]
Thanks for looking into this! Do thh be e example repos work along with the reproduction repo you created?

**Comment by volkyeth** [comment]
Yeah, it works on a local project with workspaces when using `yarn link` to test with my fork.

 For whatever reason when I install my fork from github with yarn (`yarn add -D storybook-addon-next@https://github.com/volkyeth/storybook-addon-next#hotfix/yarn-workspaces-support`) it gives me this error when starting storybook:

> info => Loading presets
ERR! Addon value should end in /register OR it should be a valid preset https://storybook.js.org/docs/react/addons/writing-presets/
ERR! storybook-addon-next

do you know what that's about?

**Comment by volkyeth** [comment]
I've added the `prepack` script to run build
this way it's possible to install the package directly from github (I.e `yarn add -D storybook-addon-next@RyanClementsHax/storybook-addon-next#main`), and the package manager will run the `build` script after installing it, creating the `dist` folder

This way it's easier to experimenting with fixes/new features that haven't been published yet

**Comment by RyanClementsHax** [comment]
> I've added the `prepack` script to run build this way it's possible to install the package directly from github (I.e `yarn add -D storybook-addon-next@RyanClementsHax/storybook-addon-next#main`), and the package manager will run the `build` script after installing it, creating the `dist` folder
> 
> This way it's easier to experimenting with fixes/new features that haven't been published yet

Oh wow thanks for adding that and contributing this fix! I really appreciate the help!

**Pull request merged**
